# Generated by Django 5.1.4 on 2025-01-02 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_business_gst"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="member_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="teammember",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
