# Generated by Django 5.1.4 on 2025-01-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_member_name_teammember_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="select_service",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="select_staff",
        ),
        migrations.RemoveField(
            model_name="services",
            name="menu_category",
        ),
        migrations.AddField(
            model_name="appointment",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="client_appointments",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appointments",
                to="api.client",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                related_name="appointments", to="api.services"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="api.teammember",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to="api.business",
            ),
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("duration_in_mins", models.PositiveIntegerField()),
                (
                    "business",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="api.business",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(related_name="packages", to="api.services"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "business",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="api.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="services",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="api.servicecategory",
            ),
        ),
    ]
