# Generated by Django 5.1.4 on 2025-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_appointment_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_name",
            field=models.CharField(max_length=50),
        ),
    ]
