# Generated by Django 5.1.4 on 2025-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_servicecategory_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Booked", "Booked"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                null=True,
            ),
        ),
    ]
