# Generated by Django 5.1.4 on 2025-01-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="services",
        ),
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.services",
            ),
        ),
    ]
