# Generated by Django 5.1.4 on 2025-01-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_appointment_services_appointment_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="status",
        ),
        migrations.AddField(
            model_name="appointment",
            name="pay_mode",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Offline",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.business",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client_appointments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appointments",
                to="api.client",
            ),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="services",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="api.teammember",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                related_name="appointments", to="api.services"
            ),
        ),
    ]
