# Generated by Django 5.1.4 on 2025-01-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_otp_delete_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="business",
        ),
        migrations.RemoveField(
            model_name="client",
            name="business",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="business",
        ),
        migrations.RemoveField(
            model_name="services",
            name="business",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="business",
        ),
        migrations.AddField(
            model_name="business",
            name="appointments",
            field=models.ManyToManyField(
                related_name="businesses", to="api.appointment"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(
                related_name="businesses", to="api.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="clients",
            field=models.ManyToManyField(related_name="businesses", to="api.client"),
        ),
        migrations.AddField(
            model_name="business",
            name="services",
            field=models.ManyToManyField(related_name="businesses", to="api.services"),
        ),
        migrations.AddField(
            model_name="business",
            name="team_members",
            field=models.ManyToManyField(
                related_name="businesses", to="api.teammember"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="api.servicecategory",
            ),
        ),
    ]
