# Generated by Django 5.1.4 on 2025-01-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_appointment_business_remove_client_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="appointments",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="businesses", to="api.appointment"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="businesses",
                to="api.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="clients",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="businesses", to="api.client"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="services",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="businesses", to="api.services"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="team_members",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="businesses", to="api.teammember"
            ),
        ),
    ]
