# Generated by Django 5.1.4 on 2025-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_business_appointments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="appointments",
        ),
        migrations.RemoveField(
            model_name="business",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="business",
            name="clients",
        ),
        migrations.AlterField(
            model_name="business",
            name="gst",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="owner_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="business",
            name="owner_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="business",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="business",
            name="salon_description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="salon_name",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="business",
            name="services",
        ),
        migrations.RemoveField(
            model_name="business",
            name="team_members",
        ),
        migrations.AddField(
            model_name="business",
            name="appointments",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="categories",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="clients",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="services",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="team_members",
            field=models.JSONField(default=list),
        ),
    ]
