# Generated by Django 5.1.4 on 2025-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_business_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="appointment_history",
        ),
        migrations.AddField(
            model_name="business",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name="business",
            name="appointments",
        ),
        migrations.RemoveField(
            model_name="business",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="business",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="business",
            name="services",
        ),
        migrations.RemoveField(
            model_name="business",
            name="team_members",
        ),
        migrations.AddField(
            model_name="business",
            name="appointments",
            field=models.ManyToManyField(
                blank=True, related_name="businesses", to="api.appointment"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="businesses", to="api.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="clients",
            field=models.ManyToManyField(
                blank=True, related_name="businesses", to="api.client"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="businesses", to="api.services"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="team_members",
            field=models.ManyToManyField(
                blank=True, related_name="businesses", to="api.teammember"
            ),
        ),
    ]
