# Generated by Django 5.1.4 on 2025-01-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_otp_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="clients",
        ),
        migrations.AddField(
            model_name="business",
            name="related_clients",
            field=models.ManyToManyField(
                blank=True, related_name="related_businesses", to="api.client"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_clients",
                to="api.business",
            ),
            preserve_default=False,
        ),
    ]
