# Generated by Django 5.1.4 on 2025-01-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_business_clients_business_related_clients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="business",
        ),
        migrations.AddField(
            model_name="business",
            name="clients",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.client"
            ),
            preserve_default=False,
        ),
    ]
