# Generated by Django 5.1.4 on 2025-01-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_client_business_business_clients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="clients",
        ),
        migrations.AddField(
            model_name="client",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_clients",
                to="api.business",
            ),
            preserve_default=False,
        ),
    ]
