# Generated by Django 5.1.4 on 2025-01-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_business_clients_client_business"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="is_available",
        ),
        migrations.AddField(
            model_name="teammember",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="api.business",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="team_members",
            field=models.ManyToManyField(
                blank=True, related_name="related_businesses", to="api.teammember"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="api.business",
            ),
        ),
    ]
