# Generated by Django 5.1.4 on 2025-01-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_teammember_is_available_teammember_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_team_members",
                to="api.business",
            ),
        ),
    ]
