# Generated by Django 5.1.4 on 2025-01-11 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_team_members_business_related_team_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_services",
                to="api.business",
            ),
            preserve_default=False,
        ),
    ]
