# Generated by Django 5.1.4 on 2025-01-11 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_services_category_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_categories",
                to="api.business",
            ),
            preserve_default=False,
        ),
    ]
