# Generated by Django 5.1.4 on 2025-01-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_servicecategory_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_appointments",
                to="api.business",
            ),
            preserve_default=False,
        ),
    ]
