# Generated by Django 5.1.4 on 2025-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_appointment_notes_appointment_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
