# Generated by Django 5.1.4 on 2025-01-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_remove_business_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="appointments",
        ),
        migrations.RemoveField(
            model_name="business",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="business",
            name="related_clients",
        ),
        migrations.RemoveField(
            model_name="business",
            name="related_team_members",
        ),
        migrations.RemoveField(
            model_name="business",
            name="services",
        ),
    ]
