# Generated by Django 5.1.4 on 2025-01-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_business_appointments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
