# Generated by Django 5.1.4 on 2025-01-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_otp_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="packages",
            field=models.ManyToManyField(
                blank=True, related_name="appointments", to="api.packages"
            ),
        ),
    ]
