# Generated by Django 5.1.4 on 2025-01-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_alter_business_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
