# Generated by Django 5.1.4 on 2025-01-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_appointment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services-images/"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="team-profiles/"),
        ),
    ]
