# Generated by Django 5.1.4 on 2025-02-05 13:47

import api.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_business_profile_img_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                validators=[api.models.validate_image_size],
            ),
        ),
    ]
