# Generated by Django 5.1.4 on 2025-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="gst",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
